name: Format

runs:
  using: "composite"
  steps:
    - name: Run pint
      run: composer pint
      shell: bash

    - name: Run eslint
      run: npm run lint
      shell: bash

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Fix styling
