name: Build PR

on:
  workflow_call:
    inputs:
      slack_webhook:
        type: string
        description: "Slack webhook URL"
        required: false

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: "postgis/postgis:17-3.5-alpine"
        env:
          PGPASSWORD: password
          POSTGRES_DB: testing
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.5"

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Checkout shared workflow repository
        uses: actions/checkout@v6
        with:
          repository: dodayslabs/.github
          path: ./.github.shared/
          ref: main

      - name: Configure composer auth
        run: composer config --global github-oauth.github.com ${{ secrets.COMPOSER_TOKEN }}

      - name: Run composer install
        run: composer install -n --prefer-dist

      - name: Build assets
        run: pnpm install --frozen-lockfile && pnpm build

      - name: Run format action
        uses: ./.github.shared/.github/actions/format

      - name: Run test action
        uses: ./.github.shared/.github/actions/test
        env:
          DB_HOST: "127.0.0.1"
          DB_PORT: ${{ job.services.postgres.ports['5432'] }}

      - name: Send Slack notification
        if: ${{ vars.SLACK_WEBHOOK }}
        uses: slackapi/slack-github-action@v2
        with:
          webhook: ${{ vars.SLACK_WEBHOOK }}
          webhook-type: incoming-webhook
          payload: |
            text: "${{ job.status }}: build for ${{ github.repository }} (PR by ${{ github.actor }}) - ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

      - name: Remove shared workflow repository
        run: rm -rf ./.github.shared

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Fix styling
